name: Coding Standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  checkcs:
    name: 'PHPCS check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: cs2pr
          coverage: none

      # Install dependencies and handle caching in one go.
      # PHPCS packages are already defined in composer.json require-dev.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: highest
          # Bust the cache at least once a month - output format: YYYY-MM-DD.
          custom-cache-suffix: $(date -u -d "-0 month -$(($(date +%d)-1)) days" "+%F")

      # Check the code-style consistency of the PHP files.
      - name: Check PHP code style
        run: vendor/bin/phpcs --report-checkstyle=./phpcs-report.xml | cs2pr
