name: Test

on:
  # Run on all pushes for default branch and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - "**.md"
      - "**.txt"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: "0 0 * * 1"
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Notes regarding supported versions in WP:
        # The base matrix contains the PHP versions which are supported on all supported WP versions.
        php: ["7.4", "8.0"]
        wp: ["latest", "6.2"]
        experimental: [false]

        include:
          # PHP 8.4 is beta-supported since WP 6.7.
          - php: "8.4"
            wp: "latest"
            experimental: false
          - php: "8.4"
            wp: "6.7"
            experimental: false
          # PHP 8.3 is beta-supported since WP 6.4.
          - php: "8.3"
            wp: "latest"
            experimental: false
          - php: "8.3"
            wp: "6.4"
            experimental: false
          # PHP 8.2 is beta-supported since WP 6.1.
          - php: "8.2"
            wp: "latest"
            experimental: false
          - php: "8.2"
            wp: "6.2"
            experimental: false
          # PHP 8.1 is beta-supported since WP 5.9 and Requests was updated in WP 6.2.
          - php: "8.1"
            wp: "latest"
            experimental: false
          - php: "8.1"
            wp: "6.2"
            experimental: false
          # Additional specific WP version builds.
          - php: "7.4"
            wp: "6.0"
            experimental: false
          - php: "8.0"
            wp: "6.3"
            experimental: false

    name: "PHP ${{ matrix.php }} - WP ${{ matrix.wp }}"

    continue-on-error: ${{ matrix.experimental }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none

      - name: Set up WordPress
        run: phpunit/install.sh wordpress_test root '' 127.0.0.1:3306 ${{ matrix.wp }}

      # Install dependencies and handle caching in one go.
      # Yoast PHPUnit Polyfills v2 handles installing the correct PHPUnit version automatically.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"
        with:
          # Bust the cache at least once a month - output format: YYYY-MM-DD.
          custom-cache-suffix: $(date -u -d "-0 month -$(($(date +%d)-1)) days" "+%F")

      - name: Run the unit tests - single site
        run: vendor/bin/phpunit

      - name: Run the unit tests - multisite
        run: vendor/bin/phpunit
        env:
          WP_MULTISITE: 1
